version: "3.9"
services:
  process-executor:
    image: lro/process-executor:latest
    build:
      context: .
      dockerfile: ./dockerfiles/process-executor/Dockerfile
    deploy:
      replicas: 1
      mode: global
      restart_policy:
        condition: on-failure
    read_only: true
    # volumes:
    #   - type: bind
    #     source: ./test.db
    #     target: /test.db
    configs:
      - source: process-executor
        target: /config.yml
        mode: 0440
    networks:
      - process-services
    depends_on:
      - db
      - nats
      - redis

  process-api:
    image: lro/process-api:latest
    build:
      context: .
      dockerfile: ./dockerfiles/process-api/Dockerfile
    deploy:
      replicas: 1
      mode: global
    #volumes:
    #  - type: bind
    #    source: ./test.db
    #    target: /test.db
    read_only: true
    ports:
      - "8080:8080"
    configs:
      - source: process-api
        target: /config.yml
        mode: 0440
    #configs:
    #  - config.yaml
    #env_file: .env
    networks:
      - process-services
    depends_on:
      - db
      - nats
      - redis
    # network_mode: "host"

  nats:
    build: ./dockerfiles/nats
    image: lro/nats
    deploy:
      restart_policy:
        condition: on-failure
    #ports:
    #  - 4222:4222
    env_file:
      - ./configs/dev/nats.env
    volumes:
      - nats:/nats
    networks:
      - process-services
  db:
    build: ./dockerfiles/db
    image: lro/db
    deploy:
      restart_policy:
        condition: on-failure
    env_file:
      - ./configs/dev/db.env
    #ports:
    #  - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - process-services
  redis:
    build: ./dockerfiles/redis
    image: lro/redis
    deploy:
      restart_policy:
        condition: on-failure
    #ports:
    #  - 6379:6379
    volumes:
      - redis:/data
    networks:
      - process-services

networks:
  process-services:
volumes:
  db:
  nats:
  redis:
configs:
  process-executor:
    file: ./configs/dev/process-executor.yml
  process-api:
    file: ./configs/dev/process-api.yml
