---
apiVersion: 1
datasources:
  - uid: "loki"
    orgId: 1
    name: "Loki"
    type: "loki"
    typeName: "Loki"
    typeLogoUrl: "public/app/plugins/datasource/loki/img/loki_icon.svg"
    access: "proxy"
    url: "${LOKI_URL}"
    password: ""
    user: ""
    database: ""
    basicAuth: false
    isDefault: true
    jsonData: {}
    readOnly: false
