---
apiVersion: 1
datasources:
  - uid: "postgres"
    orgId: 1
    name: "PostgreSQL"
    type: "postgres"
    typeName: "PostgreSQL"
    typeLogoUrl: "public/app/plugins/datasource/postgres/img/postgresql_logo.svg"
    access: "proxy"
    url: "${GF_DATABASE_HOST}"
    password: "${GF_DATABASE_PASSWORD}"
    user: "${GF_DATABASE_USER}"
    database: "${APP_DATABASE_NAME}"
    basicAuth: false
    isDefault: false
    jsonData:
      postgresVersion: 903
      sslmode: "disable"
      tlsAuth: false
      tlsAuthWithCACert: false
      tlsConfigurationMethod: "file-path"
      tlsSkipVerify: true
    readOnly: false
