CREATE DATABASE lro;
CREATE DATABASE grafana;
CREATE DATABASE kratos;

-- CREATE EXTENSION IF NOT EXISTS uuid-ossp;
-- CREATE EXTENSION IF NOT EXISTS citext;
-- CREATE EXTENSION IF NOT EXISTS hstore;
-- CREATE EXTENSION IF NOT EXISTS pg_stat_statements;
