#!/bin/bash

set -e
set -u
set -x
set -o pipefail

export PGPASSWORD="$POSTGRES_PASSWORD"
export PGUSER="$POSTGRES_USER"

for sql in \
        "CREATE USER \"${KRATOS_DATABASE_USER}\" WITH LOGIN PASSWORD '${KRATOS_DATABASE_PASSWORD}' NOSUPERUSER NOCREATEDB NOCREATEROLE INHERIT;" \
        "ALTER DATABASE \"${KRATOS_DATABASE_NAME}\" OWNER TO \"${KRATOS_DATABASE_USER}\";" \
        "ALTER ROLE \"${KRATOS_DATABASE_USER}\" SET client_encoding TO \"utf8\";" \
        "ALTER ROLE \"${KRATOS_DATABASE_USER}\" SET default_transaction_isolation TO \"read committed\";" \
        "ALTER ROLE \"${KRATOS_DATABASE_USER}\" SET timezone TO \"UTC\";" \
        "GRANT ALL PRIVILEGES ON DATABASE \"${KRATOS_DATABASE_NAME}\" TO \"${KRATOS_DATABASE_USER}\";" \
        "GRANT CREATE ON DATABASE \"${KRATOS_DATABASE_NAME}\" TO \"${KRATOS_DATABASE_USER}\";" \
        "GRANT ALL ON ALL TABLES IN SCHEMA public TO \"${KRATOS_DATABASE_USER}\";" \
        "GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO \"${KRATOS_DATABASE_USER}\";" \
        "GRANT ALL ON ALL FUNCTIONS IN SCHEMA public TO \"${KRATOS_DATABASE_USER}\";" \
; do
  psql "$KRATOS_DATABASE_NAME" -U "$PGUSER" -c "$sql";
done;
