{
 "title": "Watermill",
 "description": "Watermill is a Go library for working efficiently with message streams. It is intended for building event driven applications, enabling event sourcing, RPC over messages, sagas and basically whatever else comes to your mind. You can use conventional pub/sub implementations like Kafka or RabbitMQ, but also HTTP or MySQL binlog if that fits your use case.",
 "tags": [
  "go",
  "golang",
  "cqrs",
  "kafka",
  "event-driven"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "interval",
    "query": "15s, 30s, 1m,10m,30m,1h,6h,12h,1d"
   },
   { "name": "node", "query": "label_values(instance)" },
   { "name": "handler", "label": "handler", "query": "label_values(handler_name)" },
   { "name": "publisher", "query": "label_values(publisher_name)" }
  ]
 },
 "panels": [
  { "title": "Current stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Messages received",
   "type": "singlestat",
   "description": "Counts the messages received within the selected interval. The graph shows the historical trend of this value, also measured over the selected interval.",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(subscriber_messages_received_total{instance=~\"$node\", handler_name=~\"$handler\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Handler errors",
   "type": "singlestat",
   "description": "Counts the handler errors within the selected interval. The graph shows the historical trend of this value, also measured over the selected interval.",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(handler_execution_time_seconds_count{instance=~\"$node\", handler_name=~\"$handler\", success=\"false\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Messages published",
   "type": "singlestat",
   "description": "Counts the messages publisher within the selected interval. The graph shows the historical trend of this value, also measured over the selected interval.",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(publish_time_seconds_count{instance=~\"$node\", handler_name=~\"$handler\", success=\"true\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Publisher errors",
   "type": "singlestat",
   "description": "Counts the publisher errors within the selected interval. The graph shows the historical trend of this value, also measured over the selected interval.",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(publish_time_seconds_count{instance=~\"$node\", handler_name=~\"$handler\", success=\"false\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Subscriber count",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(count(subscriber_messages_received_total{acked=\"acked\"}) by (instance))"
    }
   ]
  },
  {
   "title": "Handler count",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(count(handler_execution_time_seconds_count{success=\"true\"}) by (instance))"
    }
   ]
  },
  {
   "title": "Publisher count",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(count(publish_time_seconds_count{success=\"true\"}) by (instance))"
    }
   ]
  },
  {
   "title": "Made by",
   "type": "text",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
   "content": "<center>\n  <a href=\"https://threedotslabs.com/\">\n    <svg\n       xmlns:svg=\"http://www.w3.org/2000/svg\"\n       xmlns=\"http://www.w3.org/2000/svg\"\n       version=\"1.1\"\n       width=\"100\"\n       height=\"100\"\n       viewBox=\"0 0 100 100\">\n      <path\n         style=\"fill:#ffffff;stroke-width:0.02\"\n         d=\"M 31.778916,99.930604 C 27.39576,98.858563 24.621347,94.358696 24.578653,90.0029 c 2.563799,-5.722986 5.686344,-11.211293 8.464703,-16.845645 2.189261,-4.353403 4.539058,-8.631413 6.597006,-13.047655 0.199946,-5.171341 0.130598,-10.398628 0.0614,-15.561986 -3.468387,-1.361218 -3.351144,-7.231458 0.360804,-8.127289 6.697684,0.0085 13.395999,-0.03612 20.093198,0.01846 3.542089,1.183583 3.529953,6.766248 0.126526,8.149373 -0.06596,5.182609 -0.02588,10.36833 0.02191,15.551439 4.9877,9.923535 10.225735,19.73149 15.112875,29.698952 0.15367,4.962538 -3.855901,10.637711 -9.203144,10.129645 -11.478179,-0.0167 -22.958055,0.0411 -34.435015,-0.0376 z M 49.517004,33.681892 c -3.49539,-0.396964 -4.085406,-5.770645 -0.677353,-6.812398 4.786757,-1.80492 6.567596,6.435435 1.505626,6.809576 l -0.828245,0.0028 z m -8.749692,-15.57129 c -3.725896,-0.337231 -5.108816,-5.824382 -1.760886,-7.723699 3.008247,-2.2390459 7.553323,1.193141 6.317934,4.699865 -0.576937,1.913074 -2.561064,3.267086 -4.557048,3.023834 z m 18.929333,-2.199243 c -4.161672,-0.05674 -6.64547,-5.620071 -3.852212,-8.7465156 2.570378,-3.6222675 8.909217,-2.0678395 9.554451,2.3324255 0.718338,3.3455981 -2.27107,6.7899561 -5.702239,6.4140901 z\">\n      </path>\n    </svg>\n  </a>\n</center>"
  },
  { "title": "Handler & publisher operations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Handler op/s",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(irate(handler_execution_time_seconds_count{instance=~\"$node\", handler_name=~\"$handler\"}[$interval])) by (handler_name, instance)",
     "legendFormat": "{{handler_name}}@{{instance}}"
    }
   ]
  },
  {
   "title": "Publish op/s",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(irate(publish_time_seconds_count{instance=~\"$node\", handler_name=~\"$handler\", publisher_name=~\"$publisher\"}[$interval])) by (handler_name, instance, publisher_name)",
     "legendFormat": "{{publisher_name}}@{{instance}}"
    }
   ]
  },
  {
   "title": "Handler duration @ $node nodes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(handler_execution_time_seconds_bucket{instance=~\"$node\", handler_name=~\"$handler\"}[$interval])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(handler_execution_time_seconds_bucket{instance=~\"$node\", handler_name=~\"$handler\"}[$interval])) by ( le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(handler_execution_time_seconds_bucket{instance=~\"$node\", handler_name=~\"$handler\"}[$interval])) by (le))",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "Publish duration @ $node nodes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(publish_time_seconds_bucket{instance=~\"$node\", handler_name=~\"$handler\", publisher_name=~\"$publisher\"}[$interval])) by (handler_name, le, publisher_name))",
     "legendFormat": "p99 {{handler_name}}→{{publisher_name}}"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(publish_time_seconds_bucket{instance=~\"$node\", handler_name=~\"$handler\", publisher_name=~\"$publisher\"}[$interval])) by (handler_name, le, publisher_name))",
     "legendFormat": "p90 {{handler_name}}→{{publisher_name}}"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(publish_time_seconds_bucket{instance=~\"$node\", handler_name=~\"$handler\", publisher_name=~\"$publisher\"}[$interval])) by (handler_name, le, publisher_name))",
     "legendFormat": "p50 {{handler_name}}→{{publisher_name}}"
    }
   ]
  },
  {
   "title": "Handler failed op/s",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(irate(handler_execution_time_seconds_count{instance=~\"$node\", handler_name=~\"$handler\", success=\"false\"}[$interval])) by (handler_name, instance)",
     "legendFormat": "{{handler_name}}@{{instance}}"
    }
   ]
  },
  {
   "title": "Publish failed op/s",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(irate(publish_time_seconds_count{instance=~\"$node\", handler_name=~\"$handler\", success=\"false\", publisher_name=~\"$publisher\"}[$interval])) by (handler_name, instance)",
     "legendFormat": "{{handler_name}}@{{instance}}"
    }
   ]
  }
 ]
}