name: process-executor
env: dev  # [dev, production]
database:
  # url: "host=db user=username password=password dbname=db port=5432 sslmode=disable TimeZone=UTC"
  # url: "postgresql://username:password@db:5432/db?sslmode=disable&TimeZone=UTC"
  url:
nats:
  url: "nats:4222"
  token:
redis:
  url: "redis:6379"
  username: ""
  password: ""
  db: 0
log:
  level: INFO
