// Package auth provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.9.1 DO NOT EDIT.
package auth

import (
	openapi_types "github.com/deepmap/oapi-codegen/pkg/types"
)

// Defines values for AuthAccountRole.
const (
	AuthAccountRoleADMIN AuthAccountRole = "ADMIN"

	AuthAccountRoleUSER AuthAccountRole = "USER"
)

// Defines values for AuthAccountStatus.
const (
	AuthAccountStatusACTIVE AuthAccountStatus = "ACTIVE"

	AuthAccountStatusDISABLED AuthAccountStatus = "DISABLED"

	AuthAccountStatusINVALID AuthAccountStatus = "INVALID"
)

// Auth User data structure
type AuthAccount struct {
	Email     openapi_types.Email `json:"email"`
	FirstName *string             `json:"first_name,omitempty"`
	LastName  *string             `json:"last_name,omitempty"`
	Role      AuthAccountRole     `json:"role"`
	Status    AuthAccountStatus   `json:"status"`
	Username  string              `json:"username"`
}

// AuthAccountRole defines model for AuthAccount.Role.
type AuthAccountRole string

// AuthAccountStatus defines model for AuthAccount.Status.
type AuthAccountStatus string

// User login form structure
type AuthForm struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}
